import { StrictMode } from 'react'
import { createRoot } from 'react-dom/client'
import AppBootstrap from './AppBootstrap'
import './styles.css'
import './app-like.css'
import './mobile-polish.css'
import './nocturne-redesign.css'
import './nocturne-header-fix.css'
import './theme-cohesion.css'
import './rush-effects.css'
import './rush-effects'
import './rush-motion-v2.css'
import './rush-motion-v2'
import './uiHotfix'

createRoot(document.getElementById('root')!).render(<StrictMode><AppBootstrap /></StrictMode>)
